### ISSUE TITLE
500 on /u/<user> when logged in as <user>

### ISSUE THREAD

**Issue by elbosso** [ascclemens/paste#236]
So I was trying to go to <route>, but then the server was all like nah, bb, 500!

What happened was that i wanted to see all by public pastes as registered user. When i tried to view all this users pastes as anonymous user - everything worked. The path was /u/<user>. To clarify: a get request on this path always results in a 500 error when logged in as <user> and always succeeds when not logged in at all

**Comment by ascclemens** [comment]
On paste.gg? Which user? I can't reproduce this.

**Comment by elbosso** [comment]
First of all, thanks for the quick reply - i read in some other issue that the project is no longer a priority for you... Second: yeah, I should have mentioned that this actually occurred in a private docker-based installation in my home lab and i can confirm that it does not happen on paste.gg - anyway thanks for looking into it! Will close the ticket, because I had some problems getting the whole thing set up on my docker machine (took me more than 10 hours and it still does not play well with my other containers) and obviously screwed something up during the process. I have already been starting to realize that i am not smart enough to get it to work locally and now I am giving up...
