### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by minijackson** [ascclemens/paste#238]
Hello!

I would like to package this awesome tool for the [NixOS](https://nixos.org/) distribution, but have found some issues with the current `v0.1.1` release:

- The Cargo.lock specifies that the version of the webserver is version `0.1.0` instead of `0.1.1` (easily fixable with a patch)
- The project fails to compile the `pear_codegen v0.0.18` dependency, complaining that the `quote` feature has been removed (less easily fixable)

So I guess my question is: are you planning on doing a release in the near future?

I have seen the `v0.2.0` milestone and looks quite featureful, so I think my question stands more for a `v0.1.2` release.

Thank you for the awesome work, and have a great day!

**Comment by ascclemens** [comment]
I am not planning on releasing a new version soon. Development has mostly stalled, since this is really a passion project that earns me no money, so I only work on it when the mood strikes. While I am invested in making sure it continues to work, I wouldn't expect any new version updates.

**Comment by minijackson** [comment]
Thanks for the clarifications! This answers my questions, then ^^
