### ISSUE TITLE
500 Internal server error while pasting

### ISSUE THREAD

**Issue by Whomsky** [ascclemens/paste#244]
So I was trying to submit a paste, but then the server was all like nah, bb, 500!

**Comment by arantesxyz** [comment]
Same here. I think the server might have a problem. Maybe it's full?

**Comment by RavingPlatypi** [comment]
Seems that its in maintenance mode right now. Haven't been able to access my pastes all day

**Comment by ascclemens** [comment]
Yup, slow maintenance.

**Comment by RavingPlatypi** [comment]
It's all good! We'll be waiting patiently :)

**Comment by ascclemens** [comment]
Restored and shouldn't have further issues.
